## Steps
1. Download all raw data for a given year and month
1. For each raw data, apply the filter before saving it
1. Transform the saved raw data into TS data
1. Convert the ts data into features and targets
1. Save the transformed data


Main objective is to write utility functions to do all these things so we can reuse them later. 

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
import os

# Add the parent directory to the Python path
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), "..")))

# Now you can import from src
from src.data_utils import load_and_process_taxi_data

In [3]:
rides = load_and_process_taxi_data(year=2023)

File already exists for 2023-01.
Loading data for 2023-01...
Total records: 3,066,766
Valid records: 2,993,140
Records dropped: 73,626 (2.40%)
Successfully processed data for 2023-01.
File already exists for 2023-02.
Loading data for 2023-02...
Total records: 2,913,955
Valid records: 2,845,058
Records dropped: 68,897 (2.36%)
Successfully processed data for 2023-02.
File already exists for 2023-03.
Loading data for 2023-03...
Total records: 3,403,766
Valid records: 3,331,705
Records dropped: 72,061 (2.12%)
Successfully processed data for 2023-03.
Successfully downloaded data for 2023-04.
Loading data for 2023-04...
Total records: 3,288,250
Valid records: 3,214,922
Records dropped: 73,328 (2.23%)
Successfully processed data for 2023-04.
Successfully downloaded data for 2023-05.
Loading data for 2023-05...
Total records: 3,513,649
Valid records: 3,435,875
Records dropped: 77,774 (2.21%)
Successfully processed data for 2023-05.
Successfully downloaded data for 2023-06.
Loading data for 202

In [4]:
rides

pickup_datetime  pickup_location_id
0        2023-01-01 00:32:10                 161
1        2023-01-01 00:55:08                  43
2        2023-01-01 00:25:04                  48
3        2023-01-01 00:03:48                 138
4        2023-01-01 00:10:29                 107
...                      ...                 ...
37463263 2023-12-31 23:04:34                 233
37463264 2023-12-31 23:08:15                  48
37463265 2023-12-31 23:16:15                 196
37463266 2023-12-31 23:21:58                 140
37463267 2023-12-31 23:10:47                 237

[37463268 rows x 2 columns]

In [5]:
from src.data_utils import transform_raw_data_into_ts_data

ts_data = transform_raw_data_into_ts_data(rides)
ts_data.head()

pickup_hour  pickup_location_id  rides
0 2023-01-01 00:00:00                   2      0
1 2023-01-01 01:00:00                   2      0
2 2023-01-01 02:00:00                   2      0
3 2023-01-01 03:00:00                   2      0
4 2023-01-01 04:00:00                   2      0

In [6]:
ts_data.shape

(2277600, 3)

In [7]:
from src.data_utils import transform_ts_data_info_features_and_target_loop

features, targets = transform_ts_data_info_features_and_target_loop(ts_data, window_size=24*28, step_size=24)


In [8]:
features

rides_t-672  rides_t-671  rides_t-670  rides_t-669  rides_t-668  \
0                0            0            0            0            0   
1                0            0            0            0            0   
2                0            0            0            0            0   
3                0            0            0            0            0   
4                0            0            0            0            0   
...            ...          ...          ...          ...          ...   
87615           25           14            5            3            7   
87616           30            7            9            6            5   
87617           50           26           17            9            8   
87618          117           88           39           19           14   
87619          120           82           61           41           13   

       rides_t-667  rides_t-666  rides_t-665  rides_t-664  rides_t-663  ...  \
0                0            0            0            0            0  ...   
1                0            0            0            0            0  ...   
2                0            0            0            0            0  ...   
3                0            0            0            0            0  ...   
4                0            0            0            0            0  ...   
...            ...          ...          ...          ...          ...  ...   
87615           16           53          133          126          136  ...   
87616           23           58          123          136          108  ...   
87617           11           43          116          137          132  ...   
87618           12           27           37           70           97  ...   
87619           12           26           37           45           99  ...   

       rides_t-8  rides_t-7  rides_t-6  rides_t-5  rides_t-4  rides_t-3  \
0              0          1          0          0          0          0   
1              0          0          0          0          0          0   
2              0          0          0          0          0          0   
3              0          0          0          0          0          0   
4              0          0          0          0          0          0   
...          ...        ...        ...        ...        ...        ...   
87615         73         62         62         58         50         48   
87616         83         64         79         65         71         72   
87617         71         81         78         60         85         63   
87618         78         84         75        100         98         88   
87619         78         85         76         95         68         76   

       rides_t-2  rides_t-1  pickup_hour  pickup_location_id  
0              0          0   2023-01-29                   2  
1              0          0   2023-01-30                   2  
2              0          0   2023-01-31                   2  
3              0          0   2023-02-01                   2  
4              0          0   2023-02-02                   2  
...          ...        ...          ...                 ...  
87615         42         37   2023-12-27                 263  
87616         75         35   2023-12-28                 263  
87617         62         37   2023-12-29                 263  
87618         77         69   2023-12-30                 263  
87619         71         61   2023-12-31                 263  

[87620 rows x 674 columns]

In [10]:
import numpy as np
window_size = 4
step_size = 1
num_windows = 4

step_size * np.arange(num_windows)[:, None]  # Output: array([[0], [1], [2], [3]])

indices = np.arange(window_size)[None, :] + step_size * np.arange(num_windows)[:, None]


In [11]:
window_size = 4
step_size = 1
num_windows = 4

In [12]:
import numpy as np
np.arange(num_windows)

array([0, 1, 2, 3])

In [13]:
np.arange(num_windows)[:, None]

array([[0],
       [1],
       [2],
       [3]])

In [14]:
step_size * np.arange(num_windows)[:, None]

array([[0],
       [1],
       [2],
       [3]])

In [15]:
indices = np.arange(window_size)[None, :] + step_size * np.arange(num_windows)[:, None]


In [16]:
np.arange(window_size)[None, :]

array([[0, 1, 2, 3]])

In [17]:
np.arange(window_size)[None, :] + step_size * np.arange(num_windows)[:, None]

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [18]:
# Array 1: A 2D array with 2 rows and 2 columns
array1 = np.array([[1, 2],
                   [3, 4]])

# Array 2: A 2D array with 2 rows and 1 column
array2 = np.array([[5],
                   [6]])

# Array 3: A 2D array with 2 rows and 1 column
array3 = np.array([[7],
                   [8]])


np.hstack([array1, array2, array3])

array([[1, 2, 5, 7],
       [3, 4, 6, 8]])

In [19]:
from src.data_utils import transform_ts_data_info_features_and_target_loop

features, targets = transform_ts_data_info_features_and_target_loop(ts_data, window_size=24*28*1, step_size=24)


In [20]:
tabular_data = features
tabular_data["target"] = targets

from src.config import TRANSFORMED_DATA_DIR
tabular_data.to_parquet(TRANSFORMED_DATA_DIR / "tabular_data.parquet", engine="pyarrow")

In [21]:
features, targets = transform_ts_data_info_features_and_target_loop(ts_data[ts_data["pickup_location_id"]==43], window_size=12, step_size=1)


In [22]:
features

rides_t-12  rides_t-11  rides_t-10  rides_t-9  rides_t-8  rides_t-7  \
0             92          81          29         15          4          4   
1             81          29          15          4          4          3   
2             29          15           4          4          3         12   
3             15           4           4          3         12         12   
4              4           4           3         12         12         23   
...          ...         ...         ...        ...        ...        ...   
8743          11          13          29         60         99        103   
8744          13          29          60         99        103        143   
8745          29          60          99        103        143        151   
8746          60          99         103        143        151        209   
8747          99         103         143        151        209        160   

      rides_t-6  rides_t-5  rides_t-4  rides_t-3  rides_t-2  rides_t-1  \
0             3         12         12         23         37         41   
1            12         12         23         37         41        102   
2            12         23         37         41        102         97   
3            23         37         41        102         97        106   
4            37         41        102         97        106        119   
...         ...        ...        ...        ...        ...        ...   
8743        143        151        209        160         98         66   
8744        151        209        160         98         66         55   
8745        209        160         98         66         55         72   
8746        160         98         66         55         72         50   
8747         98         66         55         72         50         28   

             pickup_hour  pickup_location_id  
0    2023-01-01 12:00:00                  43  
1    2023-01-01 13:00:00                  43  
2    2023-01-01 14:00:00                  43  
3    2023-01-01 15:00:00                  43  
4    2023-01-01 16:00:00                  43  
...                  ...                 ...  
8743 2023-12-31 19:00:00                  43  
8744 2023-12-31 20:00:00                  43  
8745 2023-12-31 21:00:00                  43  
8746 2023-12-31 22:00:00                  43  
8747 2023-12-31 23:00:00                  43  

[8748 rows x 14 columns]

In [23]:
ts_data[ts_data["pickup_location_id"]==43].head(36)

pickup_hour  pickup_location_id  rides
359160 2023-01-01 00:00:00                  43     92
359161 2023-01-01 01:00:00                  43     81
359162 2023-01-01 02:00:00                  43     29
359163 2023-01-01 03:00:00                  43     15
359164 2023-01-01 04:00:00                  43      4
359165 2023-01-01 05:00:00                  43      4
359166 2023-01-01 06:00:00                  43      3
359167 2023-01-01 07:00:00                  43     12
359168 2023-01-01 08:00:00                  43     12
359169 2023-01-01 09:00:00                  43     23
359170 2023-01-01 10:00:00                  43     37
359171 2023-01-01 11:00:00                  43     41
359172 2023-01-01 12:00:00                  43    102
359173 2023-01-01 13:00:00                  43     97
359174 2023-01-01 14:00:00                  43    106
359175 2023-01-01 15:00:00                  43    119
359176 2023-01-01 16:00:00                  43    103
359177 2023-01-01 17:00:00                  43     65
359178 2023-01-01 18:00:00                  43     39
359179 2023-01-01 19:00:00                  43     35
359180 2023-01-01 20:00:00                  43     32
359181 2023-01-01 21:00:00                  43     40
359182 2023-01-01 22:00:00                  43     18
359183 2023-01-01 23:00:00                  43     13
359184 2023-01-02 00:00:00                  43      2
359185 2023-01-02 01:00:00                  43      0
359186 2023-01-02 02:00:00                  43      2
359187 2023-01-02 03:00:00                  43      2
359188 2023-01-02 04:00:00                  43      0
359189 2023-01-02 05:00:00                  43      1
359190 2023-01-02 06:00:00                  43      5
359191 2023-01-02 07:00:00                  43     10
359192 2023-01-02 08:00:00                  43     16
359193 2023-01-02 09:00:00                  43     29
359194 2023-01-02 10:00:00                  43     62
359195 2023-01-02 11:00:00                  43     51

In [24]:
from src.data_utils import transform_ts_data_info_features_and_target

features, targets = transform_ts_data_info_features_and_target(ts_data[ts_data["pickup_location_id"]==43], window_size=4, step_size=1)


In [25]:
features

rides_t-4  rides_t-3  rides_t-2  rides_t-1         pickup_hour  \
0            92         81         29         15 2023-01-01 04:00:00   
1            81         29         15          4 2023-01-01 05:00:00   
2            29         15          4          4 2023-01-01 06:00:00   
3            15          4          4          3 2023-01-01 07:00:00   
4             4          4          3         12 2023-01-01 08:00:00   
...         ...        ...        ...        ...                 ...   
8751        209        160         98         66 2023-12-31 19:00:00   
8752        160         98         66         55 2023-12-31 20:00:00   
8753         98         66         55         72 2023-12-31 21:00:00   
8754         66         55         72         50 2023-12-31 22:00:00   
8755         55         72         50         28 2023-12-31 23:00:00   

      pickup_location_id  
0                     43  
1                     43  
2                     43  
3                     43  
4                     43  
...                  ...  
8751                  43  
8752                  43  
8753                  43  
8754                  43  
8755                  43  

[8756 rows x 6 columns]

In [26]:
from src.data_utils import transform_ts_data_info_features_and_target

In [27]:
features, targets = transform_ts_data_info_features_and_target(ts_data[ts_data["pickup_location_id"]==43], window_size=4, step_size=1)


In [30]:
features

rides_t-4  rides_t-3  rides_t-2  rides_t-1         pickup_hour  \
0            92         81         29         15 2023-01-01 04:00:00   
1            81         29         15          4 2023-01-01 05:00:00   
2            29         15          4          4 2023-01-01 06:00:00   
3            15          4          4          3 2023-01-01 07:00:00   
4             4          4          3         12 2023-01-01 08:00:00   
...         ...        ...        ...        ...                 ...   
8751        209        160         98         66 2023-12-31 19:00:00   
8752        160         98         66         55 2023-12-31 20:00:00   
8753         98         66         55         72 2023-12-31 21:00:00   
8754         66         55         72         50 2023-12-31 22:00:00   
8755         55         72         50         28 2023-12-31 23:00:00   

      pickup_location_id  
0                     43  
1                     43  
2                     43  
3                     43  
4                     43  
...                  ...  
8751                  43  
8752                  43  
8753                  43  
8754                  43  
8755                  43  

[8756 rows x 6 columns]

In [31]:
targets

0        4
1        4
2        3
3       12
4       12
        ..
8751    55
8752    72
8753    50
8754    28
8755    34
Name: target, Length: 8756, dtype: int16